with-expecter: true
#boilerplate-file: ".mockery_boilerplate_text.txt"
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True
disable-version-string: true

packages:
  # IAM сервис
  github.com/Alexander-Mandzhiev/school_schedule/iam/internal/service:
    config:
      include-regex: ".*Service"
  github.com/Alexander-Mandzhiev/school_schedule/iam/internal/repository:
    config:
      include-regex: ".*Repository"

  # RBAC сервис
  github.com/Alexander-Mandzhiev/school_schedule/rbac/internal/service:
    config:
      include-regex: ".*Service"
  github.com/Alexander-Mandzhiev/school_schedule/rbac/internal/repository:
    config:
      include-regex: ".*Repository"

  # gRPC клиенты IAM
  github.com/Alexander-Mandzhiev/school_schedule/iam/internal/client/grpc:
    config:
      include-regex: ".*Client"