// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: role/v1/role.proto

package role_v1

import (
	v1 "github.com/aleksandr-mv/school_schedule/shared/pkg/proto/common/v1"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на создание новой роли
type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_role_v1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Ответ с ID созданной роли
type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_role_v1_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleResponse) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

// Запрос на получение роли по ID или имени
type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *v1.GetIdentifier      `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_role_v1_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoleRequest) GetValue() *v1.GetIdentifier {
	if x != nil {
		return x.Value
	}
	return nil
}

// Ответ с данными роли
type GetRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *v1.Role               `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_role_v1_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoleResponse) GetRole() *v1.Role {
	if x != nil {
		return x.Role
	}
	return nil
}

// Запрос на обновление роли
type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_role_v1_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// Запрос на удаление роли по ID
type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_role_v1_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

// Запрос на получение списка ролей
type ListRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Опциональные фильтры
	NameFilter    *string `protobuf:"bytes,1,opt,name=name_filter,json=nameFilter,proto3,oneof" json:"name_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_role_v1_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{6}
}

func (x *ListRolesRequest) GetNameFilter() string {
	if x != nil && x.NameFilter != nil {
		return *x.NameFilter
	}
	return ""
}

// Ответ со списком ролей
type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*v1.Role             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_role_v1_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{7}
}

func (x *ListRolesResponse) GetData() []*v1.Role {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_role_v1_role_proto protoreflect.FileDescriptor

const file_role_v1_role_proto_rawDesc = "" +
	"\n" +
	"\x12role/v1/role.proto\x12\arole.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\x1a\x14common/v1/role.proto\x1a\x1bcommon/v1/annotations.proto\x1a\x1acommon/v1/identifier.proto\"T\n" +
	"\x11CreateRoleRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x02\x182R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"7\n" +
	"\x12CreateRoleResponse\x12!\n" +
	"\arole_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06roleId\"J\n" +
	"\x0eGetRoleRequest\x128\n" +
	"\x05value\x18\x01 \x01(\v2\x18.common.v1.GetIdentifierB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05value\"@\n" +
	"\x0fGetRoleResponse\x12-\n" +
	"\x04role\x18\x01 \x01(\v2\x0f.common.v1.RoleB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04role\"\x9a\x01\n" +
	"\x11UpdateRoleRequest\x12!\n" +
	"\arole_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06roleId\x12\"\n" +
	"\x04name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x02\x182H\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"6\n" +
	"\x11DeleteRoleRequest\x12!\n" +
	"\arole_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06roleId\"H\n" +
	"\x10ListRolesRequest\x12$\n" +
	"\vname_filter\x18\x01 \x01(\tH\x00R\n" +
	"nameFilter\x88\x01\x01B\x0e\n" +
	"\f_name_filter\"8\n" +
	"\x11ListRolesResponse\x12#\n" +
	"\x04data\x18\x01 \x03(\v2\x0f.common.v1.RoleR\x04data2\xa8\x03\n" +
	"\vRoleService\x12U\n" +
	"\n" +
	"CreateRole\x12\x1a.role.v1.CreateRoleRequest\x1a\x1b.role.v1.CreateRoleResponse\"\x0e\x8a\xb5\x18\n" +
	"role:write\x12K\n" +
	"\aGetRole\x12\x17.role.v1.GetRoleRequest\x1a\x18.role.v1.GetRoleResponse\"\r\x8a\xb5\x18\trole:read\x12P\n" +
	"\n" +
	"UpdateRole\x12\x1a.role.v1.UpdateRoleRequest\x1a\x16.google.protobuf.Empty\"\x0e\x8a\xb5\x18\n" +
	"role:write\x12P\n" +
	"\n" +
	"DeleteRole\x12\x1a.role.v1.DeleteRoleRequest\x1a\x16.google.protobuf.Empty\"\x0e\x8a\xb5\x18\n" +
	"role:write\x12Q\n" +
	"\tListRoles\x12\x19.role.v1.ListRolesRequest\x1a\x1a.role.v1.ListRolesResponse\"\r\x8a\xb5\x18\trole:readBJZHgithub.com/aleksandr-mv/school_schedule/shared/pkg/proto/role/v1;role_v1b\x06proto3"

var (
	file_role_v1_role_proto_rawDescOnce sync.Once
	file_role_v1_role_proto_rawDescData []byte
)

func file_role_v1_role_proto_rawDescGZIP() []byte {
	file_role_v1_role_proto_rawDescOnce.Do(func() {
		file_role_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_v1_role_proto_rawDesc), len(file_role_v1_role_proto_rawDesc)))
	})
	return file_role_v1_role_proto_rawDescData
}

var file_role_v1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_role_v1_role_proto_goTypes = []any{
	(*CreateRoleRequest)(nil),  // 0: role.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil), // 1: role.v1.CreateRoleResponse
	(*GetRoleRequest)(nil),     // 2: role.v1.GetRoleRequest
	(*GetRoleResponse)(nil),    // 3: role.v1.GetRoleResponse
	(*UpdateRoleRequest)(nil),  // 4: role.v1.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),  // 5: role.v1.DeleteRoleRequest
	(*ListRolesRequest)(nil),   // 6: role.v1.ListRolesRequest
	(*ListRolesResponse)(nil),  // 7: role.v1.ListRolesResponse
	(*v1.GetIdentifier)(nil),   // 8: common.v1.GetIdentifier
	(*v1.Role)(nil),            // 9: common.v1.Role
	(*emptypb.Empty)(nil),      // 10: google.protobuf.Empty
}
var file_role_v1_role_proto_depIdxs = []int32{
	8,  // 0: role.v1.GetRoleRequest.value:type_name -> common.v1.GetIdentifier
	9,  // 1: role.v1.GetRoleResponse.role:type_name -> common.v1.Role
	9,  // 2: role.v1.ListRolesResponse.data:type_name -> common.v1.Role
	0,  // 3: role.v1.RoleService.CreateRole:input_type -> role.v1.CreateRoleRequest
	2,  // 4: role.v1.RoleService.GetRole:input_type -> role.v1.GetRoleRequest
	4,  // 5: role.v1.RoleService.UpdateRole:input_type -> role.v1.UpdateRoleRequest
	5,  // 6: role.v1.RoleService.DeleteRole:input_type -> role.v1.DeleteRoleRequest
	6,  // 7: role.v1.RoleService.ListRoles:input_type -> role.v1.ListRolesRequest
	1,  // 8: role.v1.RoleService.CreateRole:output_type -> role.v1.CreateRoleResponse
	3,  // 9: role.v1.RoleService.GetRole:output_type -> role.v1.GetRoleResponse
	10, // 10: role.v1.RoleService.UpdateRole:output_type -> google.protobuf.Empty
	10, // 11: role.v1.RoleService.DeleteRole:output_type -> google.protobuf.Empty
	7,  // 12: role.v1.RoleService.ListRoles:output_type -> role.v1.ListRolesResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_role_v1_role_proto_init() }
func file_role_v1_role_proto_init() {
	if File_role_v1_role_proto != nil {
		return
	}
	file_role_v1_role_proto_msgTypes[4].OneofWrappers = []any{}
	file_role_v1_role_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_v1_role_proto_rawDesc), len(file_role_v1_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_v1_role_proto_goTypes,
		DependencyIndexes: file_role_v1_role_proto_depIdxs,
		MessageInfos:      file_role_v1_role_proto_msgTypes,
	}.Build()
	File_role_v1_role_proto = out.File
	file_role_v1_role_proto_goTypes = nil
	file_role_v1_role_proto_depIdxs = nil
}
