// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/annotations.proto

package common_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_common_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "common.v1.permission",
		Tag:           "bytes,50001,opt,name=permission",
		Filename:      "common/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// Право доступа в формате "resource:action"
	//
	// optional string permission = 50001;
	E_Permission = &file_common_v1_annotations_proto_extTypes[0]
)

var File_common_v1_annotations_proto protoreflect.FileDescriptor

const file_common_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1bcommon/v1/annotations.proto\x12\tcommon.v1\x1a google/protobuf/descriptor.proto:@\n" +
	"\n" +
	"permission\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\tR\n" +
	"permissionBUZSgithub.com/Alexander-Mandzhiev/school_schedule/shared/pkg/proto/common/v1;common_v1b\x06proto3"

var file_common_v1_annotations_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
}
var file_common_v1_annotations_proto_depIdxs = []int32{
	0, // 0: common.v1.permission:extendee -> google.protobuf.MethodOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_annotations_proto_init() }
func file_common_v1_annotations_proto_init() {
	if File_common_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_annotations_proto_rawDesc), len(file_common_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_annotations_proto_goTypes,
		DependencyIndexes: file_common_v1_annotations_proto_depIdxs,
		ExtensionInfos:    file_common_v1_annotations_proto_extTypes,
	}.Build()
	File_common_v1_annotations_proto = out.File
	file_common_v1_annotations_proto_goTypes = nil
	file_common_v1_annotations_proto_depIdxs = nil
}
