// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/identifier.proto

package common_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Универсальный идентификатор для поиска по ID или имени
type GetIdentifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetIdentifier_Id
	//	*GetIdentifier_Name
	Identifier    isGetIdentifier_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentifier) Reset() {
	*x = GetIdentifier{}
	mi := &file_common_v1_identifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentifier) ProtoMessage() {}

func (x *GetIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_identifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentifier.ProtoReflect.Descriptor instead.
func (*GetIdentifier) Descriptor() ([]byte, []int) {
	return file_common_v1_identifier_proto_rawDescGZIP(), []int{0}
}

func (x *GetIdentifier) GetIdentifier() isGetIdentifier_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetIdentifier) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetIdentifier_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetIdentifier) GetName() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetIdentifier_Name); ok {
			return x.Name
		}
	}
	return ""
}

type isGetIdentifier_Identifier interface {
	isGetIdentifier_Identifier()
}

type GetIdentifier_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetIdentifier_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*GetIdentifier_Id) isGetIdentifier_Identifier() {}

func (*GetIdentifier_Name) isGetIdentifier_Identifier() {}

var File_common_v1_identifier_proto protoreflect.FileDescriptor

const file_common_v1_identifier_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/v1/identifier.proto\x12\tcommon.v1\x1a\x17validate/validate.proto\"X\n" +
	"\rGetIdentifier\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01H\x00R\x02id\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x00R\x04nameB\f\n" +
	"\n" +
	"identifierBNZLgithub.com/aleksandr-mv/school_schedule/shared/pkg/proto/common/v1;common_v1b\x06proto3"

var (
	file_common_v1_identifier_proto_rawDescOnce sync.Once
	file_common_v1_identifier_proto_rawDescData []byte
)

func file_common_v1_identifier_proto_rawDescGZIP() []byte {
	file_common_v1_identifier_proto_rawDescOnce.Do(func() {
		file_common_v1_identifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_identifier_proto_rawDesc), len(file_common_v1_identifier_proto_rawDesc)))
	})
	return file_common_v1_identifier_proto_rawDescData
}

var file_common_v1_identifier_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_identifier_proto_goTypes = []any{
	(*GetIdentifier)(nil), // 0: common.v1.GetIdentifier
}
var file_common_v1_identifier_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_identifier_proto_init() }
func file_common_v1_identifier_proto_init() {
	if File_common_v1_identifier_proto != nil {
		return
	}
	file_common_v1_identifier_proto_msgTypes[0].OneofWrappers = []any{
		(*GetIdentifier_Id)(nil),
		(*GetIdentifier_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_identifier_proto_rawDesc), len(file_common_v1_identifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_identifier_proto_goTypes,
		DependencyIndexes: file_common_v1_identifier_proto_depIdxs,
		MessageInfos:      file_common_v1_identifier_proto_msgTypes,
	}.Build()
	File_common_v1_identifier_proto = out.File
	file_common_v1_identifier_proto_goTypes = nil
	file_common_v1_identifier_proto_depIdxs = nil
}
