// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/permission.proto

package common_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Право доступа
type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_common_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_common_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Permission) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_common_v1_permission_proto protoreflect.FileDescriptor

const file_common_v1_permission_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/v1/permission.proto\x12\tcommon.v1\x1a\x17validate/validate.proto\"p\n" +
	"\n" +
	"Permission\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12%\n" +
	"\bresource\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\bresource\x12!\n" +
	"\x06action\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\x06actionBNZLgithub.com/aleksandr-mv/school_schedule/shared/pkg/proto/common/v1;common_v1b\x06proto3"

var (
	file_common_v1_permission_proto_rawDescOnce sync.Once
	file_common_v1_permission_proto_rawDescData []byte
)

func file_common_v1_permission_proto_rawDescGZIP() []byte {
	file_common_v1_permission_proto_rawDescOnce.Do(func() {
		file_common_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_permission_proto_rawDesc), len(file_common_v1_permission_proto_rawDesc)))
	})
	return file_common_v1_permission_proto_rawDescData
}

var file_common_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_permission_proto_goTypes = []any{
	(*Permission)(nil), // 0: common.v1.Permission
}
var file_common_v1_permission_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_permission_proto_init() }
func file_common_v1_permission_proto_init() {
	if File_common_v1_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_permission_proto_rawDesc), len(file_common_v1_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_permission_proto_goTypes,
		DependencyIndexes: file_common_v1_permission_proto_depIdxs,
		MessageInfos:      file_common_v1_permission_proto_msgTypes,
	}.Build()
	File_common_v1_permission_proto = out.File
	file_common_v1_permission_proto_goTypes = nil
	file_common_v1_permission_proto_depIdxs = nil
}
