// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/school_schedule/rbac/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PermissionRepository is an autogenerated mock type for the PermissionRepository type
type PermissionRepository struct {
	mock.Mock
}

type PermissionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PermissionRepository) EXPECT() *PermissionRepository_Expecter {
	return &PermissionRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx
func (_m *PermissionRepository) List(ctx context.Context) ([]*model.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PermissionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PermissionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PermissionRepository_Expecter) List(ctx interface{}) *PermissionRepository_List_Call {
	return &PermissionRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *PermissionRepository_List_Call) Run(run func(ctx context.Context)) *PermissionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PermissionRepository_List_Call) Return(_a0 []*model.Permission, _a1 error) *PermissionRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PermissionRepository_List_Call) RunAndReturn(run func(context.Context) ([]*model.Permission, error)) *PermissionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewPermissionRepository creates a new instance of PermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionRepository {
	mock := &PermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
