// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/aleksandr-mv/school_schedule/rbac/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UserRoleRepository is an autogenerated mock type for the UserRoleRepository type
type UserRoleRepository struct {
	mock.Mock
}

type UserRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRoleRepository) EXPECT() *UserRoleRepository_Expecter {
	return &UserRoleRepository_Expecter{mock: &_m.Mock}
}

// AssignRole provides a mock function with given fields: ctx, userID, roleID, assignedBy
func (_m *UserRoleRepository) AssignRole(ctx context.Context, userID string, roleID string, assignedBy *string) error {
	ret := _m.Called(ctx, userID, roleID, assignedBy)

	if len(ret) == 0 {
		panic("no return value specified for AssignRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) error); ok {
		r0 = rf(ctx, userID, roleID, assignedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRoleRepository_AssignRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRole'
type UserRoleRepository_AssignRole_Call struct {
	*mock.Call
}

// AssignRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roleID string
//   - assignedBy *string
func (_e *UserRoleRepository_Expecter) AssignRole(ctx interface{}, userID interface{}, roleID interface{}, assignedBy interface{}) *UserRoleRepository_AssignRole_Call {
	return &UserRoleRepository_AssignRole_Call{Call: _e.mock.On("AssignRole", ctx, userID, roleID, assignedBy)}
}

func (_c *UserRoleRepository_AssignRole_Call) Run(run func(ctx context.Context, userID string, roleID string, assignedBy *string)) *UserRoleRepository_AssignRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *UserRoleRepository_AssignRole_Call) Return(_a0 error) *UserRoleRepository_AssignRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRoleRepository_AssignRole_Call) RunAndReturn(run func(context.Context, string, string, *string) error) *UserRoleRepository_AssignRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleUsers provides a mock function with given fields: ctx, roleID, limit, cursor
func (_m *UserRoleRepository) GetRoleUsers(ctx context.Context, roleID string, limit int32, cursor *string) ([]string, int32, *string, error) {
	ret := _m.Called(ctx, roleID, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleUsers")
	}

	var r0 []string
	var r1 int32
	var r2 *string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, *string) ([]string, int32, *string, error)); ok {
		return rf(ctx, roleID, limit, cursor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, *string) []string); ok {
		r0 = rf(ctx, roleID, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, *string) int32); ok {
		r1 = rf(ctx, roleID, limit, cursor)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int32, *string) *string); ok {
		r2 = rf(ctx, roleID, limit, cursor)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*string)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, int32, *string) error); ok {
		r3 = rf(ctx, roleID, limit, cursor)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// UserRoleRepository_GetRoleUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleUsers'
type UserRoleRepository_GetRoleUsers_Call struct {
	*mock.Call
}

// GetRoleUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - limit int32
//   - cursor *string
func (_e *UserRoleRepository_Expecter) GetRoleUsers(ctx interface{}, roleID interface{}, limit interface{}, cursor interface{}) *UserRoleRepository_GetRoleUsers_Call {
	return &UserRoleRepository_GetRoleUsers_Call{Call: _e.mock.On("GetRoleUsers", ctx, roleID, limit, cursor)}
}

func (_c *UserRoleRepository_GetRoleUsers_Call) Run(run func(ctx context.Context, roleID string, limit int32, cursor *string)) *UserRoleRepository_GetRoleUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int32), args[3].(*string))
	})
	return _c
}

func (_c *UserRoleRepository_GetRoleUsers_Call) Return(_a0 []string, _a1 int32, _a2 *string, _a3 error) *UserRoleRepository_GetRoleUsers_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *UserRoleRepository_GetRoleUsers_Call) RunAndReturn(run func(context.Context, string, int32, *string) ([]string, int32, *string, error)) *UserRoleRepository_GetRoleUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRoles provides a mock function with given fields: ctx, userID
func (_m *UserRoleRepository) GetUserRoles(ctx context.Context, userID string) ([]*model.Role, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoles")
	}

	var r0 []*model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Role, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Role); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRoleRepository_GetUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRoles'
type UserRoleRepository_GetUserRoles_Call struct {
	*mock.Call
}

// GetUserRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRoleRepository_Expecter) GetUserRoles(ctx interface{}, userID interface{}) *UserRoleRepository_GetUserRoles_Call {
	return &UserRoleRepository_GetUserRoles_Call{Call: _e.mock.On("GetUserRoles", ctx, userID)}
}

func (_c *UserRoleRepository_GetUserRoles_Call) Run(run func(ctx context.Context, userID string)) *UserRoleRepository_GetUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRoleRepository_GetUserRoles_Call) Return(_a0 []*model.Role, _a1 error) *UserRoleRepository_GetUserRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRoleRepository_GetUserRoles_Call) RunAndReturn(run func(context.Context, string) ([]*model.Role, error)) *UserRoleRepository_GetUserRoles_Call {
	_c.Call.Return(run)
	return _c
}

// HasRole provides a mock function with given fields: ctx, userID, roleID
func (_m *UserRoleRepository) HasRole(ctx context.Context, userID string, roleID string) (bool, error) {
	ret := _m.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for HasRole")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, userID, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userID, roleID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRoleRepository_HasRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRole'
type UserRoleRepository_HasRole_Call struct {
	*mock.Call
}

// HasRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roleID string
func (_e *UserRoleRepository_Expecter) HasRole(ctx interface{}, userID interface{}, roleID interface{}) *UserRoleRepository_HasRole_Call {
	return &UserRoleRepository_HasRole_Call{Call: _e.mock.On("HasRole", ctx, userID, roleID)}
}

func (_c *UserRoleRepository_HasRole_Call) Run(run func(ctx context.Context, userID string, roleID string)) *UserRoleRepository_HasRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserRoleRepository_HasRole_Call) Return(_a0 bool, _a1 error) *UserRoleRepository_HasRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRoleRepository_HasRole_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *UserRoleRepository_HasRole_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRole provides a mock function with given fields: ctx, userID, roleID
func (_m *UserRoleRepository) RevokeRole(ctx context.Context, userID string, roleID string) error {
	ret := _m.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRoleRepository_RevokeRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRole'
type UserRoleRepository_RevokeRole_Call struct {
	*mock.Call
}

// RevokeRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roleID string
func (_e *UserRoleRepository_Expecter) RevokeRole(ctx interface{}, userID interface{}, roleID interface{}) *UserRoleRepository_RevokeRole_Call {
	return &UserRoleRepository_RevokeRole_Call{Call: _e.mock.On("RevokeRole", ctx, userID, roleID)}
}

func (_c *UserRoleRepository_RevokeRole_Call) Run(run func(ctx context.Context, userID string, roleID string)) *UserRoleRepository_RevokeRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserRoleRepository_RevokeRole_Call) Return(_a0 error) *UserRoleRepository_RevokeRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRoleRepository_RevokeRole_Call) RunAndReturn(run func(context.Context, string, string) error) *UserRoleRepository_RevokeRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRoleRepository creates a new instance of UserRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRoleRepository {
	mock := &UserRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
