services: 
  kafka: 
    image: confluentinc/cp-kafka:7.9.0 
    container_name: kafka 
    env_file:
      - .env
    ports:
      - "9092:9092"
      - "${KAFKA_JMX_PORT}:${KAFKA_JMX_PORT}"
    volumes:
      - kafka_data:/var/lib/kafka/data
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.75'
        reservations:
          memory: 512M
          cpus: '0.5'
    restart: unless-stopped
    networks:
      - school_net
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "echo > /dev/tcp/localhost/9094",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  kafka-ui: 
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    env_file:
      - .env
    ports:
      - "8082:8080"
    depends_on:
      kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    restart: unless-stopped
    networks:
      - school_net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


volumes:
  kafka_data: 

networks:
  school_net:
    external: true
