apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/namespaces.yaml
  - infrastructure/configmaps.yaml
  - infrastructure/secrets.yaml
  - infrastructure/postgres.yaml
  - infrastructure/redis.yaml
  - infrastructure/kafka.yaml
  - monitoring/otel-collector.yaml
  - monitoring/prometheus.yaml
  - monitoring/alertmanager.yaml
  - services/iam.yaml
  - services/rbac.yaml
  - ingress/ingress.yaml
  - ingress/network-policies.yaml

namespace: school-schedule-system

commonLabels:
  app.kubernetes.io/name: school-schedule
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
