// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: role_permission/v1/role_permission.proto

package role_permission_v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	_ "github.com/aleksandr-mv/school_schedule/shared/pkg/proto/common/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на назначение права роли
type AssignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRequest) Reset() {
	*x = AssignRequest{}
	mi := &file_role_permission_v1_role_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRequest) ProtoMessage() {}

func (x *AssignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_permission_v1_role_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRequest.ProtoReflect.Descriptor instead.
func (*AssignRequest) Descriptor() ([]byte, []int) {
	return file_role_permission_v1_role_permission_proto_rawDescGZIP(), []int{0}
}

func (x *AssignRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

// Запрос на отзыв права у роли
type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_role_permission_v1_role_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_permission_v1_role_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_role_permission_v1_role_permission_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RevokeRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

var File_role_permission_v1_role_permission_proto protoreflect.FileDescriptor

const file_role_permission_v1_role_permission_proto_rawDesc = "" +
	"\n" +
	"(role_permission/v1/role_permission.proto\x12\x12role_permission.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\x1a\x1bcommon/v1/annotations.proto\"a\n" +
	"\rAssignRequest\x12!\n" +
	"\arole_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06roleId\x12-\n" +
	"\rpermission_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\fpermissionId\"a\n" +
	"\rRevokeRequest\x12!\n" +
	"\arole_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06roleId\x12-\n" +
	"\rpermission_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\fpermissionId2\xd7\x01\n" +
	"\x15RolePermissionService\x12^\n" +
	"\x06Assign\x12!.role_permission.v1.AssignRequest\x1a\x16.google.protobuf.Empty\"\x19\x8a\xb5\x18\x15role_permission:write\x12^\n" +
	"\x06Revoke\x12!.role_permission.v1.RevokeRequest\x1a\x16.google.protobuf.Empty\"\x19\x8a\xb5\x18\x15role_permission:writeB`Z^github.com/aleksandr-mv/school_schedule/shared/pkg/proto/role_permission/v1;role_permission_v1b\x06proto3"

var (
	file_role_permission_v1_role_permission_proto_rawDescOnce sync.Once
	file_role_permission_v1_role_permission_proto_rawDescData []byte
)

func file_role_permission_v1_role_permission_proto_rawDescGZIP() []byte {
	file_role_permission_v1_role_permission_proto_rawDescOnce.Do(func() {
		file_role_permission_v1_role_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_permission_v1_role_permission_proto_rawDesc), len(file_role_permission_v1_role_permission_proto_rawDesc)))
	})
	return file_role_permission_v1_role_permission_proto_rawDescData
}

var (
	file_role_permission_v1_role_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
	file_role_permission_v1_role_permission_proto_goTypes  = []any{
		(*AssignRequest)(nil), // 0: role_permission.v1.AssignRequest
		(*RevokeRequest)(nil), // 1: role_permission.v1.RevokeRequest
		(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
	}
)
var file_role_permission_v1_role_permission_proto_depIdxs = []int32{
	0, // 0: role_permission.v1.RolePermissionService.Assign:input_type -> role_permission.v1.AssignRequest
	1, // 1: role_permission.v1.RolePermissionService.Revoke:input_type -> role_permission.v1.RevokeRequest
	2, // 2: role_permission.v1.RolePermissionService.Assign:output_type -> google.protobuf.Empty
	2, // 3: role_permission.v1.RolePermissionService.Revoke:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_role_permission_v1_role_permission_proto_init() }
func file_role_permission_v1_role_permission_proto_init() {
	if File_role_permission_v1_role_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_permission_v1_role_permission_proto_rawDesc), len(file_role_permission_v1_role_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_permission_v1_role_permission_proto_goTypes,
		DependencyIndexes: file_role_permission_v1_role_permission_proto_depIdxs,
		MessageInfos:      file_role_permission_v1_role_permission_proto_msgTypes,
	}.Build()
	File_role_permission_v1_role_permission_proto = out.File
	file_role_permission_v1_role_permission_proto_goTypes = nil
	file_role_permission_v1_role_permission_proto_depIdxs = nil
}
