// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: role_permission/v1/role_permission.proto

package role_permission_v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RolePermissionService_Assign_FullMethodName = "/role_permission.v1.RolePermissionService/Assign"
	RolePermissionService_Revoke_FullMethodName = "/role_permission.v1.RolePermissionService/Revoke"
)

// RolePermissionServiceClient is the client API for RolePermissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RolePermissionServiceClient interface {
	// Назначение права роли
	Assign(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Отзыв права у роли
	Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type rolePermissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRolePermissionServiceClient(cc grpc.ClientConnInterface) RolePermissionServiceClient {
	return &rolePermissionServiceClient{cc}
}

func (c *rolePermissionServiceClient) Assign(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RolePermissionService_Assign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePermissionServiceClient) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RolePermissionService_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RolePermissionServiceServer is the server API for RolePermissionService service.
// All implementations must embed UnimplementedRolePermissionServiceServer
// for forward compatibility.
type RolePermissionServiceServer interface {
	// Назначение права роли
	Assign(context.Context, *AssignRequest) (*emptypb.Empty, error)
	// Отзыв права у роли
	Revoke(context.Context, *RevokeRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRolePermissionServiceServer()
}

// UnimplementedRolePermissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRolePermissionServiceServer struct{}

func (UnimplementedRolePermissionServiceServer) Assign(context.Context, *AssignRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Assign not implemented")
}

func (UnimplementedRolePermissionServiceServer) Revoke(context.Context, *RevokeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedRolePermissionServiceServer) mustEmbedUnimplementedRolePermissionServiceServer() {}
func (UnimplementedRolePermissionServiceServer) testEmbeddedByValue()                               {}

// UnsafeRolePermissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RolePermissionServiceServer will
// result in compilation errors.
type UnsafeRolePermissionServiceServer interface {
	mustEmbedUnimplementedRolePermissionServiceServer()
}

func RegisterRolePermissionServiceServer(s grpc.ServiceRegistrar, srv RolePermissionServiceServer) {
	// If the following call pancis, it indicates UnimplementedRolePermissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RolePermissionService_ServiceDesc, srv)
}

func _RolePermissionService_Assign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionServiceServer).Assign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermissionService_Assign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionServiceServer).Assign(ctx, req.(*AssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePermissionService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermissionService_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionServiceServer).Revoke(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RolePermissionService_ServiceDesc is the grpc.ServiceDesc for RolePermissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RolePermissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "role_permission.v1.RolePermissionService",
	HandlerType: (*RolePermissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Assign",
			Handler:    _RolePermissionService_Assign_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _RolePermissionService_Revoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "role_permission/v1/role_permission.proto",
}
