# ----------------------------
# Полный пример конфигурации для микросервиса
# ----------------------------

# Основные настройки приложения (rawAppConfig)
app:
  log_level: "debug"  # debug, info, warn, error
  logger_as_json: true
  migrations_dir: "db/migrations"
  swagger_path: "../shared/api/http/order/v1/order.swagger.yaml"
  swagger_ui_path: "./api/swagger-ui.html"

# Единая gRPC конфигурация (rawConfig)
grpc:
  # Настройки сервера
  host: "0.0.0.0"
  port: 50051
  timeout: "15s"
  idle_timeout: "60s"
  shutdown_timeout: "10s"
  
  # Настройки клиента
  max_recv_msg_size: 4194304  # 4MB
  max_send_msg_size: 4194304  # 4MB
  client_timeout: "5s"

# rawPostgresConfig
database:
  postgres:
    connection:
      host: "localhost"
      port: 5432
      user: "postgres"
      password: "password"
      database: "order"
      application_name: "order-service"
    pool:
      max_cons: 25
      min_cons: 5
      max_conn_lifetime: "1h"
      max_conn_idle_time: "30m"
      health_check_period: "1m"
      connect_timeout: "5s"
      shutdown_timeout: "30s"
    tls:
      enabled: false
      ssl_mode: "disable"
      ssl_cert: ""
      ssl_key: ""
      ssl_root_cert: ""
      ssl_password: ""
      ssl_crl: ""
      ssl_compression: false
  mongo:
    connection:
      host: "localhost"
      port: 27017
      user: "admin"
      password: "password"
      database: "inventory"
      auth_db: "admin"
    pool:
      max_pool_size: 100
      min_pool_size: 5
      max_conn_idle_time: "30m"
      max_connecting: 2
      connect_timeout: "10s"
      shutdown_timeout: "30s"
    tls:
      enabled: false
      certificate_key_file: ""
      ca_file: ""
      allow_invalid_certificates: false
      allow_invalid_hostnames: false

# Внешние сервисы (map[string]rawService)
services:
  inventory:
    address: "localhost"
    port: 50051
    timeout: "5s"
  payment:
    address: "localhost"
    port: 50052
    timeout: "5s"

# Redis кэш (rawRedisConfig)
redis:
  enabled: true
  connection:
    host: "localhost"
    port: 6379
    password: ""
    database: 0
  pool:
    pool_size: 10
    min_idle: 5
    max_retries: 3
    dial_timeout: "5s"
    read_timeout: "3s"
    write_timeout: "3s"
    pool_timeout: "4s"
    idle_timeout: "30m"
    idle_check_freq: "1m"

# Apache Kafka (rawKafkaConfig)
kafka:
  brokers: "localhost:9092"
  producers:
    order_paid:
      topic: "order.paid"
      enabled: true
    order_assembled:
      topic: "order.assembled"
      enabled: true
  consumers:
    order_paid:
      topic: "order.paid"
      group_id: "order-group-order-paid"
      enabled: true
    order_assembled:
      topic: "order.assembled"
      group_id: "order-group-order-assembled"
      enabled: true

# Telegram Bot (rawTelegramConfig)
telegram:
  token: "1234567890:ABCdefGHIjklMNOpqrsTUVwxyz"
  webhook_url: "https://your-domain.com/webhook/telegram"
  debug_mode: false
  timeout: 30
  max_retries: 3
