# Пример конфигурации CORS
# Соответствует структуре rawCorsConfig в platform/pkg/config/internal/network/cors.go

cors:
  # Разрешенные источники (origins)
  allowed_origins:
    - "http://localhost:3000"
  
  # Разрешенные HTTP методы
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  
  # Разрешенные заголовки
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Trace-ID"
    - "X-Request-ID"
  
  # Разрешенные заголовки для экспорта
  exposed_headers:
    - "X-Trace-ID"
    - "X-Request-ID"
  
  # Разрешить передачу учетных данных (cookies, authorization headers)
  allow_credentials: true
  
  # Максимальное время кэширования preflight запросов в секундах
  max_age: 600
