# =============================================================================
# REDIS КОНФИГУРАЦИЯ
# =============================================================================

# Включить Redis (true/false)
redis:
  enabled: true

  # Настройки подключения
  connection:
    host: "localhost"
    port: 6379
    password: ""  # Пустой пароль для локальной разработки
    database: 0   # Номер базы данных Redis (0-15)

  # Настройки пула соединений
  pool:
    # Размер пула соединений
    pool_size: 10
    
    # Минимальное количество простаивающих соединений
    min_idle: 5
    
    # Максимальное количество попыток переподключения
    max_retries: 3
    
    # Таймауты
    dial_timeout: "5s"      # Таймаут установки соединения
    read_timeout: "3s"      # Таймаут чтения
    write_timeout: "3s"     # Таймаут записи
    pool_timeout: "4s"      # Таймаут ожидания из пула
    
    # Настройки простаивающих соединений
    idle_timeout: "30m"     # Время простоя соединения
    idle_check_freq: "1m"   # Частота проверки простаивающих
