# Пример конфигурации Telegram бота
telegram:
  # Токен бота от @BotFather (обязательно)
  token: "1234567890:ABCdefGHIjklMNOpqrsTUVwxyz"
  
  # URL для webhook (опционально, для webhook режима)
  webhook_url: "https://your-domain.com/webhook/telegram"
  
  # Режим отладки (опционально)
  debug_mode: false
  
  # Таймаут для HTTP запросов в секундах (опционально, по умолчанию 30)
  timeout: 30
  
  # Максимальное количество попыток при ошибках (опционально, по умолчанию 3)
  max_retries: 3
