# Пример конфигурации транспортных протоколов (HTTP, gRPC)
# Соответствует структурам rawHTTPConfig, grpcRawConfig, grpcClientLimitsRaw в platform/pkg/config/internal/transport/

# HTTP сервер (rawHTTPConfig)
http_server:
  host: "0.0.0.0"
  port: 3000
  read_header_timeout: "5s"
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"
  max_header_bytes: 1048576
  shutdown_timeout: "10s"
  handler_timeout: "15s"

# gRPC сервер (grpcRawConfig)
grpc_server:
  host: "0.0.0.0"
  port: 50051
  timeout: "15s"
  idle_timeout: "60s"
  shutdown_timeout: "10s"

# gRPC клиентские лимиты (grpcClientLimitsRaw)
grpc_client_limits:
  max_recv_msg_size: 4194304  # 4MB
  max_send_msg_size: 4194304  # 4MB
  timeout: "5s"

# TLS конфигурация для транспортного слоя
tls:
  enabled: false
  cert_file: "/path/to/cert.pem"
  key_file: "/path/to/key.pem"
  ca_file: "/path/to/ca.pem"
