services: 
  cassandra:
    image: cassandra:4.1.3
    container_name: cassandra
    env_file:
      - .env
    ports:
      - "${CASSANDRA_PORT}:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: ${CASSANDRA_HEALTHCHECK_INTERVAL}
      timeout: ${CASSANDRA_HEALTHCHECK_TIMEOUT}
      retries: ${CASSANDRA_HEALTHCHECK_RETRIES}
      start_period: ${CASSANDRA_HEALTHCHECK_START_PERIOD}
    restart: unless-stopped
    networks:
      - school_net

  jaeger:
    image: jaegertracing/jaeger:2.6.0
    container_name: jaeger
    env_file:
      - .env
    ports:
      - "${JAEGER_UI_PORT}:16686"
    depends_on:
      cassandra:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:${JAEGER_UI_PORT}"]
      interval: ${JAEGER_HEALTHCHECK_INTERVAL}
      timeout: ${JAEGER_HEALTHCHECK_TIMEOUT}
      retries: ${JAEGER_HEALTHCHECK_RETRIES}
      start_period: ${JAEGER_HEALTHCHECK_START_PERIOD}
    restart: unless-stopped
    networks:
      - school_net

volumes:
  cassandra_data:
  jaeger_data:
  jaeger_key:

networks:
  school_net:
    external: true
