services:
  placeholder:
    image: alpine
    command:
      ["sh", "-c", "echo 'This is a placeholder service' && sleep infinity"]
    networks:
      - school_net
    env_file:
      - .env

networks:
  school_net:
    name: school_net
    external: false
