// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user_role/v1/user_role.proto

package user_role_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _user_role_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on AssignRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AssignRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AssignRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AssignRequestMultiError, or
// nil if none found.
func (m *AssignRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AssignRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = AssignRequestValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetRoleId()); err != nil {
		err = AssignRequestValidationError{
			field:  "RoleId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.AssignedBy != nil {

		if err := m._validateUuid(m.GetAssignedBy()); err != nil {
			err = AssignRequestValidationError{
				field:  "AssignedBy",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return AssignRequestMultiError(errors)
	}

	return nil
}

func (m *AssignRequest) _validateUuid(uuid string) error {
	if matched := _user_role_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// AssignRequestMultiError is an error wrapping multiple validation errors
// returned by AssignRequest.ValidateAll() if the designated constraints
// aren't met.
type AssignRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AssignRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AssignRequestMultiError) AllErrors() []error { return m }

// AssignRequestValidationError is the validation error returned by
// AssignRequest.Validate if the designated constraints aren't met.
type AssignRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AssignRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AssignRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AssignRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AssignRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AssignRequestValidationError) ErrorName() string { return "AssignRequestValidationError" }

// Error satisfies the builtin error interface
func (e AssignRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAssignRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AssignRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AssignRequestValidationError{}

// Validate checks the field values on RevokeRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RevokeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RevokeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RevokeRequestMultiError, or
// nil if none found.
func (m *RevokeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RevokeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = RevokeRequestValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetRoleId()); err != nil {
		err = RevokeRequestValidationError{
			field:  "RoleId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RevokeRequestMultiError(errors)
	}

	return nil
}

func (m *RevokeRequest) _validateUuid(uuid string) error {
	if matched := _user_role_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// RevokeRequestMultiError is an error wrapping multiple validation errors
// returned by RevokeRequest.ValidateAll() if the designated constraints
// aren't met.
type RevokeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevokeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevokeRequestMultiError) AllErrors() []error { return m }

// RevokeRequestValidationError is the validation error returned by
// RevokeRequest.Validate if the designated constraints aren't met.
type RevokeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevokeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevokeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevokeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevokeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevokeRequestValidationError) ErrorName() string { return "RevokeRequestValidationError" }

// Error satisfies the builtin error interface
func (e RevokeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevokeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevokeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevokeRequestValidationError{}

// Validate checks the field values on GetUserRolesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserRolesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserRolesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserRolesRequestMultiError, or nil if none found.
func (m *GetUserRolesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserRolesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = GetUserRolesRequestValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetUserRolesRequestMultiError(errors)
	}

	return nil
}

func (m *GetUserRolesRequest) _validateUuid(uuid string) error {
	if matched := _user_role_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetUserRolesRequestMultiError is an error wrapping multiple validation
// errors returned by GetUserRolesRequest.ValidateAll() if the designated
// constraints aren't met.
type GetUserRolesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserRolesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserRolesRequestMultiError) AllErrors() []error { return m }

// GetUserRolesRequestValidationError is the validation error returned by
// GetUserRolesRequest.Validate if the designated constraints aren't met.
type GetUserRolesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserRolesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserRolesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserRolesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserRolesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserRolesRequestValidationError) ErrorName() string {
	return "GetUserRolesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserRolesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserRolesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserRolesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserRolesRequestValidationError{}

// Validate checks the field values on GetUserRolesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserRolesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserRolesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserRolesResponseMultiError, or nil if none found.
func (m *GetUserRolesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserRolesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUserRolesResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUserRolesResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUserRolesResponseValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetUserRolesResponseMultiError(errors)
	}

	return nil
}

// GetUserRolesResponseMultiError is an error wrapping multiple validation
// errors returned by GetUserRolesResponse.ValidateAll() if the designated
// constraints aren't met.
type GetUserRolesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserRolesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserRolesResponseMultiError) AllErrors() []error { return m }

// GetUserRolesResponseValidationError is the validation error returned by
// GetUserRolesResponse.Validate if the designated constraints aren't met.
type GetUserRolesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserRolesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserRolesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserRolesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserRolesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserRolesResponseValidationError) ErrorName() string {
	return "GetUserRolesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserRolesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserRolesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserRolesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserRolesResponseValidationError{}

// Validate checks the field values on GetRoleUsersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRoleUsersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRoleUsersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRoleUsersRequestMultiError, or nil if none found.
func (m *GetRoleUsersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRoleUsersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetRoleId()); err != nil {
		err = GetRoleUsersRequestValidationError{
			field:  "RoleId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Limit != nil {

		if val := m.GetLimit(); val < 1 || val > 100 {
			err := GetRoleUsersRequestValidationError{
				field:  "Limit",
				reason: "value must be inside range [1, 100]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.Cursor != nil {
		// no validation rules for Cursor
	}

	if len(errors) > 0 {
		return GetRoleUsersRequestMultiError(errors)
	}

	return nil
}

func (m *GetRoleUsersRequest) _validateUuid(uuid string) error {
	if matched := _user_role_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetRoleUsersRequestMultiError is an error wrapping multiple validation
// errors returned by GetRoleUsersRequest.ValidateAll() if the designated
// constraints aren't met.
type GetRoleUsersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRoleUsersRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRoleUsersRequestMultiError) AllErrors() []error { return m }

// GetRoleUsersRequestValidationError is the validation error returned by
// GetRoleUsersRequest.Validate if the designated constraints aren't met.
type GetRoleUsersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRoleUsersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRoleUsersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRoleUsersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRoleUsersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRoleUsersRequestValidationError) ErrorName() string {
	return "GetRoleUsersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRoleUsersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRoleUsersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRoleUsersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRoleUsersRequestValidationError{}

// Validate checks the field values on GetRoleUsersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRoleUsersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRoleUsersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRoleUsersResponseMultiError, or nil if none found.
func (m *GetRoleUsersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRoleUsersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetUserIds() {
		_, _ = idx, item

		if err := m._validateUuid(item); err != nil {
			err = GetRoleUsersResponseValidationError{
				field:  fmt.Sprintf("UserIds[%v]", idx),
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	// no validation rules for Limit

	// no validation rules for HasMore

	if m.NextCursor != nil {
		// no validation rules for NextCursor
	}

	if len(errors) > 0 {
		return GetRoleUsersResponseMultiError(errors)
	}

	return nil
}

func (m *GetRoleUsersResponse) _validateUuid(uuid string) error {
	if matched := _user_role_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetRoleUsersResponseMultiError is an error wrapping multiple validation
// errors returned by GetRoleUsersResponse.ValidateAll() if the designated
// constraints aren't met.
type GetRoleUsersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRoleUsersResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRoleUsersResponseMultiError) AllErrors() []error { return m }

// GetRoleUsersResponseValidationError is the validation error returned by
// GetRoleUsersResponse.Validate if the designated constraints aren't met.
type GetRoleUsersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRoleUsersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRoleUsersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRoleUsersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRoleUsersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRoleUsersResponseValidationError) ErrorName() string {
	return "GetRoleUsersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRoleUsersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRoleUsersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRoleUsersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRoleUsersResponseValidationError{}
