extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  resource:
    attributes:
      - key: deployment.environment
        value: "development"
        action: insert
      - key: collector.domain
        value: "metrics"
        action: insert
  batch:
    send_batch_size: 1024
    timeout: "1s"
    send_batch_max_size: 1024
  memory_limiter:
    limit_mib: 400
    check_interval: "1s"

exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    tls:
      insecure: true
  debug:
    verbosity: "normal"

service:
  extensions: [health_check]
  telemetry:
    metrics:
      level: detailed
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheusremotewrite, debug]
