extensions:
  health_check:
    endpoint: "0.0.0.0:${CORE_OTEL_COLLECTOR_HEALTH_PORT}"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:${OTEL_GRPC_PORT}"

processors:
  resource:
    attributes:
      - key: deployment.environment
        value: ${ENVIRONMENT}
        action: insert
      - key: collector.domain
        value: metrics
        action: insert
  batch:
    send_batch_size: ${OTEL_BATCH_SIZE}
    timeout: ${OTEL_BATCH_TIMEOUT}
    send_batch_max_size: ${OTEL_BATCH_SIZE}
  memory_limiter:
    limit_mib: 400

exporters:
  prometheusremotewrite:
    endpoint: "http://${PROMETHEUS_HOST}:${PROMETHEUS_PORT}/api/v1/write"
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
    sending_queue:
      enabled: true
  debug:
    verbosity: ${OTEL_LOG_LEVEL}

service:
  extensions: [health_check]
  telemetry:
    metrics:
      level: detailed
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheusremotewrite, debug]
