apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-config
  namespace: school-schedule-services
data:
  development.yaml: |
    server:
      http:
        host: "0.0.0.0"
        port: 8080
      grpc:
        host: "0.0.0.0"
        port: 50052
    
    database:
      write:
        host: "postgres-rbac"
        port: 5432
        database: "rbac"
        user: "postgres"
        password: "rbac_password"
        ssl_mode: "disable"
      read:
        host: "postgres-rbac"
        port: 5432
        database: "rbac"
        user: "postgres"
        password: "rbac_password"
        ssl_mode: "disable"
    
    redis:
      cluster:
        nodes: ["redis-cluster:6379"]
        password: ""
    
    logger:
      level: "info"
      format: "json"
      otlp:
        enable: true
        endpoint: "http://otel-collector:4317"
    
    metric:
      enable: true
      endpoint: "http://otel-collector:4317"
    
    tracing:
      enable: true
      endpoint: "http://otel-collector:4317"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-service
  namespace: school-schedule-services
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rbac-service
  template:
    metadata:
      labels:
        app: rbac-service
    spec:
      containers:
      - name: rbac-service
        image: school-schedule/rbac:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50052
          name: grpc
        env:
        - name: CONFIG_PATH
          value: "/app/config/development.yaml"
        volumeMounts:
        - name: rbac-config
          mountPath: /app/config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: rbac-config
        configMap:
          name: rbac-config
---
apiVersion: v1
kind: Service
metadata:
  name: rbac-service
  namespace: school-schedule-services
spec:
  selector:
    app: rbac-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 50052
      targetPort: 50052
  type: ClusterIP
