global:
  scrape_interval:     15s # Как часто собирать метрики
  evaluation_interval: 15s # Как часто вычислять правила агрегации и алертинга

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "otel-collector"
    static_configs:
      - targets: [ "otel-collector:8888" ]

