services:
  otel-collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otel-collector
    env_file:
      - .env
    ports:
      - "${OTEL_GRPC_PORT}:4317"
      - "${OTEL_COLLECTOR_METRICS_PORT}:8888"
      - "${OTEL_COLLECTOR_HEALTH_PORT}:13133"
    restart: unless-stopped
    networks:
      - school_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${OTEL_COLLECTOR_HEALTH_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  school_net:
    external: true
