version: '3.8'

services:
  otel-collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otel-collector
    env_file:
      - .env
    environment:
      - OTEL_GRPC_PORT=${OTEL_GRPC_PORT:-4317}
      - OTEL_COLLECTOR_METRICS_PORT=${OTEL_COLLECTOR_METRICS_PORT:-8888}
      - OTEL_BATCH_SIZE=${OTEL_BATCH_SIZE:-1000}
      - OTEL_BATCH_TIMEOUT=${OTEL_BATCH_TIMEOUT:-5s}
      - OTEL_LOG_LEVEL=${OTEL_LOG_LEVEL:-detailed}
      - OTEL_MEMORY_LIMIT_MIB=${OTEL_MEMORY_LIMIT_MIB:-512}
      - OTEL_MEMORY_SPIKE_LIMIT_MIB=${OTEL_MEMORY_SPIKE_LIMIT_MIB:-128}
      - OTEL_JAEGER_HOST=${OTEL_JAEGER_HOST:-jaeger}
      - OTEL_JAEGER_PORT=${OTEL_JAEGER_PORT:-4317}
      - OTEL_ELASTICSEARCH_HOST=${OTEL_ELASTICSEARCH_HOST:-elasticsearch}
      - OTEL_ELASTICSEARCH_PORT=${OTEL_ELASTICSEARCH_PORT:-9200}
      - OTEL_PROMETHEUS_HOST=${OTEL_PROMETHEUS_HOST:-prometheus}
      - OTEL_PROMETHEUS_PORT=${OTEL_PROMETHEUS_PORT:-9090}
      - TRACING_SAMPLE_RATIO=${TRACING_SAMPLE_RATIO:-100}
      - CORE_OTEL_COLLECTOR_HEALTH_PORT=${CORE_OTEL_COLLECTOR_HEALTH_PORT:-13133}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - JAEGER_HOST=${OTEL_JAEGER_HOST:-jaeger}
      - JAEGER_PORT=${OTEL_JAEGER_PORT:-4317}
      - ELASTICSEARCH_HOST=${OTEL_ELASTICSEARCH_HOST:-elasticsearch}
      - ELASTICSEARCH_PORT=${OTEL_ELASTICSEARCH_PORT:-9200}
      - PROMETHEUS_HOST=${OTEL_PROMETHEUS_HOST:-prometheus}
      - PROMETHEUS_PORT=${OTEL_PROMETHEUS_PORT:-9090}
    ports:
      - "${OTEL_GRPC_PORT:-4317}:4317"
      - "${OTEL_COLLECTOR_METRICS_PORT:-8888}:8888"
      - "13133:13133"
    restart: unless-stopped
    networks:
      - school_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:13133"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  school_net:
    external: true
