// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RolePermissionServiceInterface is an autogenerated mock type for the RolePermissionServiceInterface type
type RolePermissionServiceInterface struct {
	mock.Mock
}

type RolePermissionServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *RolePermissionServiceInterface) EXPECT() *RolePermissionServiceInterface_Expecter {
	return &RolePermissionServiceInterface_Expecter{mock: &_m.Mock}
}

// Assign provides a mock function with given fields: ctx, roleID, permissionID
func (_m *RolePermissionServiceInterface) Assign(ctx context.Context, roleID string, permissionID string) error {
	ret := _m.Called(ctx, roleID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, roleID, permissionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RolePermissionServiceInterface_Assign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assign'
type RolePermissionServiceInterface_Assign_Call struct {
	*mock.Call
}

// Assign is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - permissionID string
func (_e *RolePermissionServiceInterface_Expecter) Assign(ctx interface{}, roleID interface{}, permissionID interface{}) *RolePermissionServiceInterface_Assign_Call {
	return &RolePermissionServiceInterface_Assign_Call{Call: _e.mock.On("Assign", ctx, roleID, permissionID)}
}

func (_c *RolePermissionServiceInterface_Assign_Call) Run(run func(ctx context.Context, roleID string, permissionID string)) *RolePermissionServiceInterface_Assign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *RolePermissionServiceInterface_Assign_Call) Return(_a0 error) *RolePermissionServiceInterface_Assign_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RolePermissionServiceInterface_Assign_Call) RunAndReturn(run func(context.Context, string, string) error) *RolePermissionServiceInterface_Assign_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, roleID, permissionID
func (_m *RolePermissionServiceInterface) Revoke(ctx context.Context, roleID string, permissionID string) error {
	ret := _m.Called(ctx, roleID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, roleID, permissionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RolePermissionServiceInterface_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type RolePermissionServiceInterface_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - permissionID string
func (_e *RolePermissionServiceInterface_Expecter) Revoke(ctx interface{}, roleID interface{}, permissionID interface{}) *RolePermissionServiceInterface_Revoke_Call {
	return &RolePermissionServiceInterface_Revoke_Call{Call: _e.mock.On("Revoke", ctx, roleID, permissionID)}
}

func (_c *RolePermissionServiceInterface_Revoke_Call) Run(run func(ctx context.Context, roleID string, permissionID string)) *RolePermissionServiceInterface_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *RolePermissionServiceInterface_Revoke_Call) Return(_a0 error) *RolePermissionServiceInterface_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RolePermissionServiceInterface_Revoke_Call) RunAndReturn(run func(context.Context, string, string) error) *RolePermissionServiceInterface_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewRolePermissionServiceInterface creates a new instance of RolePermissionServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRolePermissionServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RolePermissionServiceInterface {
	mock := &RolePermissionServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
